### ISSUE TITLE
Support testify/mockery in thriftrw-yarpc-go

### ISSUE THREAD

**Issue by Willyham** [yarpc/yarpc-go#1245]
We have a large project that already uses testify/mock and mockery. We would like to be able to use these packages to mock our thrift clients.

Is there any plan to support generating mockery for testing instead of gomock? Would it be possible to add a --mockery flag to the yarpc-thrift-plugin package to support this?

**Comment by abhinav** [comment]
There is no plan to do this at this time but we'll welcome a PR if you
implement the feature.

If it's done as part of the YARPC plugin, you'll probably want to add a flag
that lets users pick between gomock and mockery since the mocks use the
package name `${service}mock` (and there can be only one). You can also make a
standalone plugin for it instead, and use `-no-gomock` with the YARPC plugin.

**Comment by peter-edge** [comment]
Closing this as wontfix since we don't have plans to do this and it shouldn't be tracked as such, but @Willyham feel free to send a PR for this.
