### ISSUE TITLE
Enforce timeout set on context

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#198]
We should blowup if a timeout hasn't been set on a context, like tchannel currently does:

```
tchannel.SystemError{code:0x6, msg:"timeout required", wrapped:error(nil)}
```

Instead of leaking the TChannel error, we should detect this in a single place for all transports and emit a specific YARPC error.

**Comment by breerly** [comment]
@bombela please verify on both HTTP and TCH that an error is thrown, and that it is a YARPC error, and not a transport error that we are leaking.

**Comment by bombela** [comment]
Its all good and fine for HTTP as we handle both sides ourselves.

For tchannel, you get the error:

```
Received unexpected error "missing TTL"
```

Tchannel returns this error at the client side and server side. We also handle this on the server side as well.

**Comment by breerly** [comment]
When TChannel returns the error, is it wrapped in a YARPC error, or do we leak the transport-level error directly?

**Comment by bombela** [comment]
As written above, we do not wrap the tchannel error.

**Comment by bombela** [comment]
We talked about enforcing that every transports checks for the presence of the deadline in the context. We can achieve this in 3 ways:

1. make sure that all transports are returning a proper error when no deadline is available on context
2. offer a common set of functions that all transports can use, for example `standardTransportPreconditionCheck(req, meta, ctx, ...) error` 
3. wrap all use of transports forcefully into a 'standard checks transports'

Since getting the deadline is done via `context.Deadline() -> (deadline time, ok bool)`, and we should be checking the `ok` (we should be we don't because forgot to test it). I feel the best is to simply offer a function newDeadlineMissingError, and go for option 1.

**Comment by abhinav** [comment]
What about validating this in the `ValidatorOutbound` (internal/request/
validator_outbound.go)? All outbounds are wrapped in that by
`Dispatcher.Channel`.

**Comment by bombela** [comment]
This is effectively option 3 then, and it looks like its doing all of the tests already, including the deadline test. I didn't even realized we had that. Also, we never call it.

**Comment by bombela** [comment]
Interesting it is called "ValidatorOutbound" but it is only called in the handler side (http & tchannel), which is effectively an extension of the inbound.

**Comment by abhinav** [comment]
@bombela What? ValidatorOutbound is applied to outbounds when `Channel` is
called. That's client side.

```
func (d dispatcher) Channel(service string) transport.Channel {
	if out, ok := d.Outbounds[service]; ok {
		// ...
		out = request.ValidatorOutbound{Outbound: out}
		return transport.IdentityChannel(d.Name, service, out)
	}
	// ...
}
```

**Comment by abhinav** [comment]
It's the same validation logic as inbounds (implemented in internal/request/
validator.go).

**Comment by bombela** [comment]
ahah I was writing down this discovery. Just realized that yes, so technically, this ticket is resolved. Next time @breerly should ask you directly ^^
