### ISSUE TITLE
Receipts Baggage

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#213]
Per discussion with @prashantv and @nomis52, we should add the transport-level response header:

```
Rpc-ProcessedBy=<hostport>
```

I imagine something like so:

``` go
resp, respMeta, err := client.Call(....)

// ProcessedBy contains a struct implementing the HostPort int
respMeta.ProcessedBy.HostPort()
respMeta.ProcessedBy.Host()
respMeta.ProcessedBy.Port()
```

This will be pretty crucial for logging, reporting, and debugging.

**Comment by prashantv** [comment]
It'll most likely be multiple host:ports, since once call can end up calling many different requests. The tricky part is how to deal with fan out and merging the response headers if multiple RPCs are required to service a single request.

E.g.
```
svc1 -> svc2 -> [svc3, svc4]
```

svc2 makes calls in parallel and waits for them to response, so we want to merge them, and the final response should have something like:
```
processed-by: svc1:1234, svc2: 2345, svc3: 3456, svc4: 4567
```

**Comment by kriskowal** [comment]
This is a context property with merge semantics. Should be under `Context-` and will need commutative semantics.

**Comment by breerly** [comment]
Another option is that this is just a piece of regular response context, where:

- applications are required to reverse propagate the context manually, e.g. set the response context in their handler to the "sum" of response contexts for all outbound calls made.
- applications decide merge logic, or we ship a standard merger (aka a list of hosts up until a branch).

**Comment by breerly** [comment]
If that's the case, then we won't need special development for this, it will just take advantage of our response context paradigm.

**Comment by kriskowal** [comment]
Recommending we name this feature “receipts”.

**Comment by breerly** [comment]
@kriskowal I'm onboard with that. @abhinav @prashantv @nomis52 you agree?

**Comment by prashantv** [comment]
Sure sounds good to me.

**Comment by kriskowal** [comment]
I’m adding this as a feature to consider post-1.0.0.

**Comment by kriskowal** [comment]
This is not possible to implement reliably without reverse context propagation. We’ve elected not to implement reverse context propagation.

**Comment by kriskowal** [comment]
It is however possible to add a one-hop response header indicating the task that handled (not proxied) the request. Folks have asked for this feature, but it complicates dev-in-prod since the host:port doesn’t stretch over NAT. Folks who want this tend to be better served by a handle-or-forward service.
