### ISSUE TITLE
Thrift Call Interface

### ISSUE THREAD

**Issue by kriskowal** [yarpc/yarpc-go#280]
I’m proposing that instead of clever use of optional arguments carried by the context object, that we carry optional arguments as hidden properties of the argument struct, and instead of wrapping the channel with a client, make the channel the client interface.

``` go
ch := dispatcher.Channel("myservice")
ctx, resBody, err := &myserviceclient.GetValueArgs{Key: "..."}.Call(ctx, ch)
ctx, resBody, err := &myserviceclient.GetValueArgs{Key: "..."}.WithHeader("x", "y").Call(ctx, ch)
```

The generated argument struct would need to embed a hidden property to carry meta.

``` go
type GetValueArgs struct {
    caller *thrift.Caller

    Key string
}

func (args *GetValueArgs) WithHeader(k, v string) *GetValueArgs {
  args.caller.WithHeader(k, v)
  return args
}

func (args *GetValueArgs) Call(ctx context.Context, ch yarpc.Channel) (context.Context, *GetValueResponse, error) {
  ctx, body, err := args.caller.Call(ctx, ch, thrift.ToWire(args))
  // ...
  var resBody GetValueResponse
  thrift.FromWire(body, &resBody)
  return ctx, &resBody, err
}
```

Where `thrift.Caller` is defined in `yarpc` like so,

``` go
package thrift

type Caller struct {
    Headers yarpc.Headers
}

func (c *Caller) WithHeader(k, v string) {
  c.Headers = c.Headers.With(k, v)
}

func (c *Caller) Call(ctx context.Context, ch yarpc.Channel, reqBody wire.Value) (context.Context, wire.Value, error) {
  // ...
}
```

Thrift callers would implement a smattering of these carrier methods like WithHeader and Call. If an IDL names a property similarly, we would suffix the _.

please discuss @yarpc/golang

**Comment by prashantv** [comment]
This is an interesting approach, I think @abhinav was thinking of something similar but just for calls initially.

I'd prefer to keep the generated code as minimal as possible and avoid it changing too often, so I considered embedding `Caller` into the generated struct, but that could causes potential clashes in future (e.g., we might add a `WithHeaders` but the user might have a field named `WithHeaders` already).

There's a similar issue as we add new methods though, since previously compiling code may start to fail since the method name clashes.

It seems a little strange that the generated code for an IDL file is tightly coupled to the meta objects in YARPC.

**Comment by abhinav** [comment]
The coupling between the library code and the generated code won't be too much
of a problem if we make the generated code verify the library version as per
https://github.com/thriftrw/thriftrw-go/issues/115.

However, I still dislike the idea of generated code changing significantly
because we added a new attribute or method to `thrift.Caller`. For example, if
we add a `WithTimeout` method, now any code that was previously using a
`WithTimeout` attribute now has to use `WithTimeout_`. Preferably we want user
identifiers and our methods to be in different namespaces.

What about,

```go
call := keyvalueclient.NewGetValueCall(&keyvalueclient.GetValueArgs{...})
call.WithHeader(k, v)
call.Do(ctx, ch)
```

Where

```go
package keyvalueclient

import ".../yarpc-go/encoding/thrift"

type GetValueCall struct {
    thrift.Call // library controls methods defined on Call
}

type GetValueArgs struct {
    Key string  // user controls this namespace
}

func NewGetValueCall(args *GetValueArgs) *GetValueCall {
    return &GetValueCall{
        thrift.NewCall("KeyValue", "getValue", args.ToWire()),
    }
}

func (call *GetValueCall) Do(ctx context.Context, ch yarpc.Channel) (context.Context, *GetValueResponse, error) {
    ctx, wireBody, err := call.Call.Do(ctx, ch)
    // ...
    
    var resBody GetValueResult
    err := resBody.FromWire(wireBody)
    // ...
    
    return ctx, resBody, err
}
```

**Comment by kriskowal** [comment]
@abhinav +1 I think we can live with the redundancy. This is Go. This also clearly separates the YARPC binding from the ThriftRW model generation.

**Comment by prashantv** [comment]
I'm not a fan of the stutter in `keyvalueclient.NewGetValueCall(&keyvalueclient.GetValueArgs{..})`. 

If we want to go down this route, we can try to avoid the `GetValueCall` and have a single `thrift.Call` instead:
```go
type GetValueArgs keyvalue.GetValueArgs

func (args *GetValueArgs) ToYARPCCall() [...]

```

and then we create an interface in yarpc/thrift (the following would be part of the library, not generated code):
```go

type YARPCArgs interface {
   // method to write out args, similar to TStruct?
  ToYARPCCall() [...]
}

func NewCall(YARPCArgs) *thrift.Call
```

You can use the call to add meta information, while the underlying args can serialize itself and return information about the specific method etc.

**Comment by kriskowal** [comment]
We are closing in on 1.0.0 and this issue is settled.
