### ISSUE TITLE
Move test deps to glide.yaml's testImport key

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#310]
Our `glide.yaml`, and the `glide.yaml`'s of our deps should not list their test deps the `import` section. Instead, they should be moved to the `testImport` section like so:

```
import:
   # main deps
testImport:
   # test deps
```

Keeping these deps in the import section adds unnecessary constraints to the consumers of our libraries, essentially forcing them to use the same versions of the testing tools our libraries use in their application.

Solve this in:
- [x] yarpc-go (#852)
- [ ] thriftrw-go
- [ ] opentracing-go
- [ ] tchannel-go

**Comment by breerly** [comment]
Tried to give this a shot for yarpc-go, but ran into this issue: https://github.com/Masterminds/glide/issues/597

**Comment by kriskowal** [comment]
Punting to triage after 1.0.0.

**Comment by kriskowal** [comment]
Still blocking on glide.

**Comment by peter-edge** [comment]
This should be done, I did this in one of my cleanups. `github.com/stretcher/testify` still has to be `imports` because non `_test.go` files reference it, same with `github.com/golang/mock`, `github.com/crossdock/crossdock-go`, etc. The things that could be moved to `testImports` shoul be by now.

@breerly @kriskowal
