### ISSUE TITLE
[Peerlist] Discuss changes to the ChoosePeer PeerList function

### ISSUE THREAD

**Issue by willhug** [yarpc/yarpc-go#457]
The current ChoosePeer function returns a peer and an error.  After the choose, we update the peer's pending count using the StartRequest function on the peer. In a least-pending list this could have a race condition where we don't update the peer's pending count fast enough and get multiple requests going to the same peer.

In order to solve this, we need to adjust how some of the peer selection logic might work to allow a peerlist to control the incrementing of the pending count.

This would likely mean changing the ChoosePeer function to return a "Stop/EndRequest" function along with the peer.

Additionally, since we probably want to update the Least-pending list while we're in the lock, we'll need to either: 
1) Increment the list's "pending count" for the peer (without changing the peer)
2) Allow updates to a peer's pending count without immediately notifying all of it's subscribers (because that would cause a deadlock when notifying the least-pending list).

Thoughts?

**Comment by kriskowal** [comment]
**Weird/Bad idea**: It might be good for the peer.StartRequest() method to take the peer list as an argument. That we can suppress notification to the originating peer list.

**Comment by kriskowal** [comment]
We’ve addressed this. Choose() returns an end request function. The peer list is obliged for performance reasons to retain an end request function for every peer in its internal book keeping, so these are reusable. The peer list can adjust its internal book keeping before releasing the lock, and send notifications after releasing the lock. The notification gets broadcast back to the peer list, reacquiring a lock and probably doing nothing since it has already adjusted the pending count internally.
