### ISSUE TITLE
Extract Start/Stop function into Lifecycle interface

### ISSUE THREAD

**Issue by willhug** [yarpc/yarpc-go#464]
The Start/Stop pattern is used almost all objects in YARPC.  Based on feedback for other instances, we should have a common interface for controlling the lifecycle of objects

```
type Lifecycle interface {
  Start() Error
  Stop() Error
}
```

The only issue is that outbounds & inbounds currently add objects to be passed in on start.  To get around this we can change the objects to take dependencies/ServiceDetails through other functions, or potentially splitting out just the `Stop` method and leaving `Start` alone

**Comment by kriskowal** [comment]
I think @nomis52 has it aright. The Start() is irrelevant. The "lifecycle manager" is only concerned about Stop() so the interface should be called Stopper. Anyone using this would likely invoke Start() and add the Stopper to a group, so that the root Stopper can stopper all Stoppers for graceful stopping.

**Comment by willhug** [comment]
Is the plan then to create the objects in a particular order?  (E.g. we'd want the outbounds to be "started"/prepared for requests before we start taking inbound requests)

**Comment by kriskowal** [comment]
Scoping this down to #523
