### ISSUE TITLE
Reserve first byte of RPC marshaling for version - oneway

### ISSUE THREAD

**Issue by AlexAPB** [yarpc/yarpc-go#487]
This applies to an upcoming PR #486 that provides request serialization for oneway transports

When marshaling an RPC request and its context to bytes, we should reserve the first byte in the byte array for a version number.

1 - thrift,  2 - proto, 3 - etc

This allows us to unmarshal an arbitrary array of bytes according to the proper encoding we use, provides us a path off of thrift and lets us support different RPC serialization methods simultaneously.

**Comment by kriskowal** [comment]
Does this apply specifically to our special transport envelope utility for transports like Redis, but not for transports like TChannel and HTTP/1.1? We could alternately put the number on the Thrift struct.

**Comment by abhinav** [comment]
@kriskowal Yeah, this is for the oneway transport envelope utility.

We're imagining a scenario where we want to use say, protobuf to encode the
requests instead. We can't make that switch under the current format because
there's no negotiation of the encoding format. Instead if we use,

```
+---+--------~~
| 1 | Payload
+---+--------~~
```

We can let the first byte decide what format the payload is in.

If/when we change the format, we would first add support in the decoder for
the new format, add an opt-in in the encoder to use the new format, and then
after a reasonable amount of time, flip the encoder over to the new format.

**Comment by breerly** [comment]
Is this for existing transports or just for the Oneway utility? We should clarify in the title.
