### ISSUE TITLE
Rearrange yarpc folder structure to isolate interfaces from concrete implementations

### ISSUE THREAD

**Issue by willhug** [yarpc/yarpc-go#551]
One of the issues we've been running into with yarpc is circular imports between the interface layers of the code and the concrete implementations.  This is a proposed folder structure that will isolate the api layer of our code into a single directory (giving transport/encoding/extension authors a single place to check for meeting interface demands).  The top-level is what service owners should be dealing with (dispatcher/reqmeta/resmeta).  And the concrete implementations of transports and encodings are in their own folders.  The idea is that nothing in `api` should ever be dependent on files outside the `api` folder.

```
yarpc-go/
│   README.md
│   dispatcher.go
│   res_meta.go
│   req_meta.go
└───api/
│   └───transport/
│   │   │    transporttest/
│   │   │    peer.go
│   │   │    outbound.go
│   │   │    inbound.go
│   │   │    transport.go
│   │   │    ...
│   └───encoding/
│   │   └    ...
│   └───middleware/
│       └    ...
└───transport/
│   └───http/
│   └───tchannel/
│   └───x/
│   │  └─── redis/
└─── peer (hostport/roundrobin/etc)/
└─── serialize/
└───encoding/
│   └───raw/
│   └───json/
│   └───thrift/
└───middleware/
│   └───.../
└───internal (crossdock, etc)/
```

Thoughts?

**Comment by bombela** [comment]
This does look reasonable at first glance.

**Comment by kriskowal** [comment]
I propose s/api/interfaces/

**Comment by breerly** [comment]
I'm onboard because:

1. We can reserve the top-level dir for service authors
2. The `api/` will be useful to solve circular imports going forward, and to centralize the pieces contributors of extension points, encodings, and transports will find useful.
3. Concrete implementations exist as top-level packages

I also think this structure is reasonable to bring to Java, and gives us far more room to grow in the future.

Let's be sure to do this quickly though, it will make any PRs in flight a nightmare to rebase.

**Comment by kriskowal** [comment]
:ok:
