### ISSUE TITLE
Expose a way to construct BadRequestError for transport/encoding authors

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#586]
We need to expose `yarpc/internal/errors.HandlerBadRequestError` as 
`transport.BadRequestError` so that transport and encoding authors can
build these themselves.

**Comment by breerly** [comment]
Suggest putting them in `yarpc/api/errors` or `yarpc/api/transport`.

The `api/` folder is a good fit for these since these are shapes which contain no implementation, and get *used* by transport and encoding authors.

Another place to put them might be `yarpc/errors`, if we think that handlers might want to explicitly raise these in certain scenarios in the future.

**Comment by abhinav** [comment]
If we want to create `yarpc/api/errors` or `yarpc/errors`, we'll want to move
`transport.Is{BadRequest|Unexpected|Timeout}Error` there as well.

**Comment by abhinav** [comment]
It might make sense to put this in `api/transport` since these are transport-specific errors.

**Comment by abhinav** [comment]
Resolved #588
