### ISSUE TITLE
1st-class Auth error(s)

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#687]
Originally I thought that BadRequestError would be enough to represent auth errors, but that actually seems incorrect, as the middleware won't be able to differentiate an auth error from another type of bad request. 

Instead, we might want to make a 1st-class auth error in YARPC. Middleware can *raise* this error, but YARPC needs to know how to convert the generic error to the correct wire response (401 for example) so that it can wake it up on the client side.

We might even need separate AuthN and AuthZ errors, depending on how we see these being used. 

@yarpc/golang thoughts?

**Comment by anuptalwalkar** [comment]
Any thoughts on this? yarpc errors are currently package internal, so we will need a separate errors package (similar to http status codes?) to consume and bind with the response.

**Comment by abhinav** [comment]
We chose a very minimal initial set of errors with plans to expand on it.
AuthN and AuthZ errors sound reasonable to me. If we do this, we'll have to
figure out what these will look like in TChannel because TChannel error frames
don't support them (http://tchannel.readthedocs.io/en/latest/protocol/#error-0xff).

RE: errors package: We plan on exposing YARPC error constructors in the
transport package (https://github.com/yarpc/yarpc-go/pull/607).

**Comment by kriskowal** [comment]
This relates to gRPC and HTTP generally since there are ways to express this error class on the transport layer, among some other cases. For this I propose:

```go
yarpc.PermissionDeniedError(message)
yarpc.PermissionDeniedErrorf(message, ...)
yarpc.IsPermissionDeniedError(err)

yarpc.UnauthenticatedError(message)
yarpc.UnauthenticatedErrorf(message, ...)
yarpc.IsUnauthenticatedError(err)
```

The same pattern applies to other gRPC cases.

- NotFound
- ResourceExhausted
- FailedPrecondition
- Aborted
- OutOfRange
- UnimplementedError
- UnavailableError in gRPC parlance maps to both Busy and Declined in TChannel. We could pick one or make distinct error behaviors visible.

These errors may or may not be accompanied by a response, depending on whether the error cases are expressible in the encoding. Thrift for example can express all of these error cases as an application error. Protobuf doesn’t typically with gRPC, but that's not a limitation over YARPC.

How to communicate these error cases varies by transport and whether the response body is available.

Over TChannel, we have the application error bit and the message, but we can’t express anything else unless there's a response body. If there is a response body in the encoding, we can express these cases with an `Rpc-Error` response header.

Over gRPC and HTTP there are codes for each of these cases.
