### ISSUE TITLE
Testing YARPC flow locally

### ISSUE THREAD

**Issue by glibsm** [yarpc/yarpc-go#731]
I've briefly talked with @breerly and @abhinav about the this, filing the issue for broader discussion

For the purposes of this ticket, I will use the following real scenario: injecting a context-aware logger (with tracing information) into the YARPC UberFx handlers. In other words, I want to add an inbound middleware for all handlers that creates an instance of `ulog.Logger` with tracing fields already marshaled in and attaches it on the context. 

Question is: how do I test as much of that end-to-end as possible? 

Ideally I'd create a sample handler that can retrieve said logger and inspect the fields, and create some sort of an in memory YARPC setup to simulate calling it from the outside.

I believe there are other scenarios of testing middlewares or other parts of the YARPC stack that could benefit from said setup.

**Comment by willhug** [comment]
Hey Glib, are we thinking about an integration test or starting up an application with a logger and calling into it directly through something like yab?

For starting up an application we'd probably follow similar semantics for normal yarpc applications, the unfortunate thing would be that it'd be difficult to programmatically assert on the results of the service unless the logger was configured to write to some file we could assert the results of, it could also be flaky as a result of too many moving parts.

For the integration test scenario there are a couple of ways to test middleware:

1) You can create a single dispatcher in an integration test that calls into itself:
```
loggerWithExpectations := MockLogger(t)
loggerWithExpectations.Expect()...
http:= NewHTTPTransport()
dispatcher := NewDispatcher(Config{
  inbound: http.NewInbound(1234),
  middleware: fxMiddleware(loggerWithExpectations),
  outbound: "client" -> http.NewOutbound("localhost:1234")
})
dispatcher.register(Handler(func (ctx...) {
  logger := fx.GetLogger(ctx)
  logger.log("ha")
}
client := someClient(dispatcher.clientConfig("client")
dispatcher.Start()
client.Call()
```

2) You can create two dispatchers (they might need to share the transport depending on the transport type, but as long as we aren't sending traffic as we stop the dispatchers we shouldn't have issues with transports being stopped in the wrong order).
```
loggerWithExpectations := MockLogger(t)
loggerWithExpectations.Expect()...
http:= NewHTTPTransport()
Indispatcher := NewDispatcher(Config{
  inbound: http.NewInbound(1234),
  middleware: fxMiddleware(loggerWithExpectations),
})
Indispatcher.register(Handler(func (ctx...) {
  logger := fx.GetLogger(ctx)
  logger.log("ha")
}
Outdispatcher := NewDispatcher(Config{
    outbound: "client" -> http.NewOutbound("localhost:1234")
})

client := someClient(Outdispatcher.clientConfig("client"))
Indispatcher.Start()
Outdispatcher.Start()
client.Call()
```

3) We can isolate the tests to just the handler by applying the middleware directly to the handler and making the call ourselves:

```
loggerWithExpectations := MockLogger(t)
loggerWithExpectations.Expect()...
middleware := fxMiddleware(loggerWithExpectations)
handlerProcedure := ToProcedure(func (ctx, req, resw) { // New function
  logger := fx.GetLogger(ctx)
  logger.log("ha")
})

handlerWithMiddleware := middlewareapi.ApplyUnaryInbound( // located in /api/middleware
  handlerProcedure.HandlerSpec.Unary(),
  middleware.Unary,
)
handlerWithMiddleware.Handle(ctx, req, resw) // if all we care about is the context, we might be able to ignore the req and resw.
```

The first two options are a bit weird because we have to pick a fixed port for requests, which means we could have conflicts with other tests that use the same port.  Ideally we'd have a way to have an inbound request an ephemeral port that we could grab and pass to the outbound we're using.  That may be what we want to do if none of these other options work. 

Depending on how "end-to-end" this needs to be, my recommendation would be the third option because it gets rid of issues with transports altogether (which would always be before middleware/handlers) and focuses on making sure that the middleware is doing what we want it to, as a result it would be less flaky.

Will the logger be injected directly into the uberfx middleware?  Or will we be grabbing it from somewhere else?

**Comment by willhug** [comment]
One thing that might make it nicer for option 3 would be to add a wrapper that creates a ClientConfig to call directly into a Procedure's function, that way we could make calls from the Raw/Json/Thrift clients into the servers instead of needing to "fake" the procedure type

```
handler := myserviceserver.New(thriftHandler)
handler = WrapWithMiddleware(handler, uberFXInboundMiddleware)
client := myserviceclient.New(FakeClientConfig(handler))

client.MyCustomFunction(ctx, 'blah')
```

**Comment by breerly** [comment]
@glibsm what are you imagining? Something like this?

```
mem := InMemory.NewTransport()

dispatcher := NewDispatcher(Config{
  inbound: mem.Inbound(),
  outbound: "client" -> mem.Outbound(),

  middleware: fxMiddleware(loggerWithExpectations),
})

client := client.New(dispatcher.ClientConfig("client"))
client.CallMyselfInMem()
```

Something like the above, where you don't have to fuss with ports or the network?

**Comment by glibsm** [comment]
Apologies for missing the replies, yarpc emails go to my personal address attached to github :(

@breerly yeah something like that. Essentially I want to have YARPC call my handlers, rather than doing it directly.

**Comment by breerly** [comment]
@glibsm you can change that in your org preferences :)

OK - I'll jam w/ the team on this, and see what we can come up with.

**Comment by alsamylkin** [comment]
Any update on it? We'd really appreciate this and use in FX.

**Comment by kriskowal** [comment]
Assigning this to @breerly to put this on the roadmap or follow up.

**Comment by peter-edge** [comment]
Is this still an issue?

**Comment by breerly** [comment]
@peter-edge can you link to the docs describing how to write an integration test against self?

**Comment by breerly** [comment]
On second thought, now that yarpcfx does this, this issue isn't relevant anymore.
