### ISSUE TITLE
Provide means to obtain the originating IP address / host from inbound requests

### ISSUE THREAD

**Issue by bradbl** [yarpc/yarpc-go#809]
Currently the name of the calling service is available via the transport.Request object but there seems to be no way of determining the IP address or host name of the originating request. This is useful for logging & auditing scenarios.

**Comment by abhinav** [comment]
Hello, can you elaborate on the use case a bit more?

Specifically, do you want the IP of the caller who made the current incoming
request or the IP of the caller who made the original request say, three hops
ago, which caused the current request to be made?

Because it's not very obvious what value you would get out of the single-hop
address. It'll just say so-and-so application server or routing proxy made the
request to you.

**Comment by bradbl** [comment]
I meant the IP of the caller who made the original request, possibly three hops ago.

**Comment by breerly** [comment]
Since YARPC supports multiple transports, we can't assume that there will always be an IP/host origin. For example, queues could have a different origin.

Instead, I propose the following:

We add a `OriginToken() string` to https://godoc.org/go.uber.org/yarpc#Call

`OriginToken()` would return a string representation identifying *where* the message came from. Example values could include:

- `tchannel:10.0.4.21`
- `http:10.0.5.3`
- `grpc:11.0.1.9`
- `cherami:/some/consumer/grpc`
- `kafka:some-topic`

This should be enough to audit *where* messages are orginating, both in middleware for every request and in individual handlers.

@bradbl does this sound like it would work?

**Comment by bradbl** [comment]
Yes, this sounds like a good solution.

**Comment by breerly** [comment]
Closing in favor of #810
