### ISSUE TITLE
Add OriginToken() to yarpc.Call

### ISSUE THREAD

**Issue by breerly** [yarpc/yarpc-go#810]
As discussed in #809 

Let's add`OriginToken() string` to https://godoc.org/go.uber.org/yarpc#Call

`OriginToken()` would return a string representation identifying where the message came from. 

Example values could include:

* `tchannel:10.0.4.21`
* `http:10.0.5.3`
* `grpc:11.0.1.9`
* `cherami:/some/consumer/grpc` 
* `kafka:some-topic`

This should be enough to audit where messages are originating, both in middleware for every request and in individual handlers.

**Comment by breerly** [comment]
@yarpc/golang please discuss

**Comment by akshayjshah** [comment]
The "original caller" for an RPC seems like a very murky concept - unless we can get some clarity there, I'm reluctant to expose this.

Consider these call graphs:

```
A -> B: A is clearly the origin
A -> statically configured HAProxy -> B: A is probably the origin
A -> proxy that shards along business domains -> B: is A the origin, or does B have enough business logic to be the origin?
A -> caching proxy -> B: again, does the cache count as the origin here?
A -> tee -> B: should all of B, C, and D see A as the origin?
         \_> C
          \_> D
```

@bradbl can you tell us a little more about what you're planning to do with this information? It might help us figure out how best to help you.

**Comment by bradbl** [comment]
Sure, I can share my use case. I have a security sensitive service where we audit all requests made to the service. The Security Response team had requested that in addition to what we are currently auditing that we also audit source IP information. This helps them, upon review of the audit logs, to help tell a story about who did what, when and from where.  In this context, I believe origin should be interpreted as the actor who initiated the request rather than intermediaries who may have participated in routing decisions.

**Comment by kriskowal** [comment]
@bradbl Would it be adequate to expose the trace ID in logs, and collect the call graph from tracing?

**Comment by bradbl** [comment]
I think there a few problems with relying on tracing to solve this problem. 

1. Tracing is often subject to sampling policies which means for an arbitrary individual request tracing data might be missing. 
2. Having to go through the tracing logs to determine the originating actor introduces indirection during investigations. Most of the audit information is available one place, but to find this data one has to go to a different place.

**Comment by akshayjshah** [comment]
@bradbl Perhaps we can discuss in person or over videoconference. It's a little difficult to discuss the complexities here without leaking lots of internal stuff that's not (AFAIK) public.

Again, this may be completely doable, I just want to make sure that the APIs we *can* introduce will solve your problem.

**Comment by akshayjshah** [comment]
Discussed in person. Conclusions:

* The service in question likely needs to support non-YARPC callers, so it can't take a hard dependency on YARPC injecting baggage or headers. Clarified with Brad that we're not scheduling work on YARPC-Python/Java/C++.
* In general, I'm reluctant to re-invent our old HTTP header system as YARPC baggage.

Solutions:
* Ideally, the service giving out AuthN tokens would be the source of truth for this information. Other services should only need to log the token, since they should be able to look up the token owner's details later.
* In the short term, adding this as an explicit part of the request payload is easy and works equally well across callers.
* In the medium term, we can contact the other folks looking for this sort of feature and figure out the problems they're trying to solve.
* If it'll solve problems for users, we can definitely add an OriginToken-like API that propagates information across hops.

**Comment by kriskowal** [comment]
Scrubbing the backlog. Let’s revive this if necessary going forward.

**Comment by blampe** [comment]
@arturaslap needs source IP as well, can we do something here that Just Works™ and doesn't require coordination with callers?

**Comment by abhinav** [comment]
This has some overlap with #753. Can we implement #753, and introduce a `Origin` baggage which contains the RemotePeer for the original call?

**Comment by abhinav** [comment]
Closing in favor of #753
