### ISSUE TITLE
TestTChannelTracerDepth2 flaky

### ISSUE THREAD

**Issue by peter-edge** [yarpc/yarpc-go#854]
```
--- FAIL: TestTChannelTracerDepth2 (0.01s)
	Error Trace:	tracer_test.go:235
			tracer_test.go:231
	Error:      	Not equal: 
	            	expected: 4
	            	received: 3
	Messages:   	generates inbound and outband spans
```

**Comment by willhug** [comment]
Looks like this one is also happening with TestTChannelTracerDepth.

```
--- FAIL: TestTChannelTracer (0.01s)
	Error Trace:	tracer_test.go:178
			tracer_test.go:174
	Error:      	Not equal: 
	            	expected: 2
	            	received: 1
	Messages:   	generates inbound and outband spans
```

Took a look at the code, and this might be happening due to a race condition with finishing the opentracing span on TChannel inbounds.

The inbound finishes/closes the span __after__ it's finished sending the response back.  
https://github.com/uber/tchannel-go/blob/dev/fragmenting_writer.go#L272
https://github.com/uber/tchannel-go/blob/dev/inbound.go#L384

this means that there's a possible race where our assertion happens before the inbound is done cleaning up the tracer span.

To fix this we'll probably need to rework how this test works.

**Comment by peter-edge** [comment]
@abhinav can we disable these tests until we fix them? We should create an issue to fix these, and do it sooner than later, but until then we are spending a lot of time on restarting travis builds.

**Comment by peter-edge** [comment]
This is still happening https://travis-ci.org/yarpc/yarpc-go/jobs/217585683 @akshayjshah

**Comment by akshayjshah** [comment]
That build passed; do you still have a link to the one that failed?

**Comment by peter-edge** [comment]
Shoot, I restarted that one to get it to pass, but it had failed with the same error as in the description of this issue.

**Comment by peter-edge** [comment]
Here https://travis-ci.org/yarpc/yarpc-go/jobs/217678350

**Comment by kriskowal** [comment]
Spotted in the wild as well.

```
--- FAIL: TestTChannelTracerDepth2 (0.01s)
	Error Trace:	tracer_test.go:238
			tracer_test.go:235
	Error:      	Not equal: 
	            	expected: 4
	            	received: 3
	Messages:   	generates inbound and outband spans
```

Going to back up @peter-edge. Let's disable the test until I can spare some time to address the problem.

**Comment by akshayjshah** [comment]
Sure, works for me.

**Comment by peter-edge** [comment]
Should we keep this open to track fixing this instead of skipping it?

**Comment by akshayjshah** [comment]
Yeah, definitely.
