### ISSUE TITLE
make cover: cover.html gets lost inside container

### ISSUE THREAD

**Issue by abhinav** [yarpc/yarpc-go#974]
Without SUPPRESS_DOCKER, `make cover` generates a coverage report into `cover.html` but it gets lost once the Docker container exits. Can we copy it out somehow? Possibly by generating it into a `build/` directory which gets volume-mounted.

**Comment by peter-edge** [comment]
Is this still happening?

**Comment by abhinav** [comment]
Yes. Running `make cover` still does not produce a `cover.*.html` in the current directory. The following lines explicitly appear in the log

```
go tool cover -html=coverage.main.txt -o cover.main.html
go tool cover -html=coverage.x.txt -o cover.x.html
```

So those files are generated inside the Docker container and lost when it exits.

**Comment by peter-edge** [comment]
I mount the working directory into the container for `make generate`, we
could do this for `make cover` too.

**Comment by peter-edge** [comment]
@abhinav I'd like to leave this as is - to do this, `make cover` will need to mount a volume as you describe to do this simply. The problem here is that we don't want to assume we can mount volumes when using `make cover` as we want to allow `make cover` on a remote host running the Docker daemon. Locally everything just magically works on Mac if you have your Docker host running locally because Docker for mac mounts a few directories through to the hypervisor, and on Linux it works locally too. For remote Docker daemons, calling volume mounting will fail, which could affect Travis in the future.

If you really want the html, you can suppress docker. Can we close this as wontfix?

**Comment by abhinav** [comment]
I don't feel strongly about it. Let's close it and come back to it if someone else wants this too.

**Comment by peter-edge** [comment]
Closing, for anyone who might find this later, you can just do `SUPPRESS_DOCKER=1 make cover` and you will have the html file. The tradeoff of doing a volume mount here isn't what I'd want to do.
